"""bedtrim.py - cut the transcribed beds down for the traced build.

WHY THIS EXISTS.  `make debug` is the same program plus -DDEBUG, and the
trace facility costs 3 671 bytes the machine does not have: 2 936 of code,
246 of read-only data, 374 of BSS, against 324 free.  Something has to give,
and the choice was between taking music out of the shipped game or taking it
out of the traced build alone.  The game keeps its music.

WHAT IT DOES.  Takes the generated bed sources - tools/songs-midi.mml and
src/song_beds.h - and writes trimmed copies holding the first N beds.  The
traced build compiles those instead, so it carries fewer songs and fits.
Production reads the untrimmed originals and is byte-for-byte unaffected.

WHY NOT ZERO BEDS.  music.c declares `bed_song_id[BED_SONG_COUNT]` and
music.h defines BED_LAST_SONG as BED_SONG_COUNT - 1.  At zero that is a
zero-length array and an unsigned -1, so an empty bed set would mean editing
the music engine - and a traced build whose engine differs from the shipped
one is not tracing the shipped program.  N is therefore at least 1.

WHY NOT midibed.py.  That transcribes assets/midi, and assets/ is not
published in this repository, so the generated sources are all there is to
work from.  This trims what exists rather than re-deriving it.

    python3 tools/bedtrim.py <keep> <in.mml> <in-beds.h> <out.mml> <out-beds.h>
"""

import re
import sys


def write_if_changed(path, text):
    """Leave the file alone when it already says this.

    The Makefile runs this tool on every `make debug`, because the bed count
    is a variable and make cannot see a variable change.  Rewriting unchanged
    files would move their timestamps and relink the traced build every time;
    writing only on a real change keeps that to when it is warranted.
    """
    try:
        if open(path, encoding="utf-8").read() == text:
            return False
    except OSError:
        pass
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return True


def blocks(mml):
    """The mml as (leading text, [(name, text), ...])."""
    parts = re.split(r'(?m)^(?=; \S+ - )', mml)
    head, songs = parts[0], []
    for p in parts[1:]:
        m = re.search(r'(?m)^song (\S+)', p)
        if m:
            songs.append((m.group(1), p))
    return head, songs


def main():
    if len(sys.argv) != 6:
        print(__doc__)
        return 2
    keep = int(sys.argv[1])
    src_mml, src_beds, out_mml, out_beds = sys.argv[2:6]

    head, songs = blocks(open(src_mml, encoding="utf-8").read())
    if not songs:
        print("bedtrim: no songs found in %s" % src_mml, file=sys.stderr)
        return 1
    if keep < 1:
        print("bedtrim: keep must be at least 1 - see the note in this file",
              file=sys.stderr)
        return 1

    kept = songs[:keep]
    keptnames = set(n for n, _ in kept)

    body = ("; GENERATED by tools/bedtrim.py from %s - do not edit.\n"
            "; The first %d of %d beds, for the traced build only.\n"
            "; The shipped game uses the full set; see this tool's header.\n\n"
            % (src_mml, len(kept), len(songs)))
    for _, text in kept:
        body += text if text.endswith("\n") else text + "\n"
    changed_mml = write_if_changed(out_mml, body)

    # The bed list is an X-macro table; the entries whose song is gone go with
    # it, and the count comes from what is left rather than being restated.
    beds = open(src_beds, encoding="utf-8").read()
    rows = re.findall(r'(?m)^ *X\((SONG_\w+),\s*("[^"]*")\)\s*\\\s*$', beds)
    if not rows:
        print("bedtrim: no X() rows in %s" % src_beds, file=sys.stderr)
        return 1

    def wanted(sym):
        return sym[len("SONG_"):].lower() in keptnames

    rows = [r for r in rows if wanted(r[0])]
    if len(rows) != len(kept):
        print("bedtrim: %d beds kept but %d rows matched - the bed list and "
              "the mml disagree" % (len(kept), len(rows)), file=sys.stderr)
        return 1

    hdr = ("/* GENERATED by tools/bedtrim.py from %s - do not edit.\n"
           "** The first %d of %d beds, for the traced build only. */\n\n"
           "#ifndef URFINKEL_SONG_BEDS_H\n#define URFINKEL_SONG_BEDS_H\n\n"
           '#include "song_dbg_ids.h"\n\n'
           "#define BED_SONG_COUNT %d\n\n"
           "#define BED_SONG_LIST \\\n"
           % (src_beds, len(rows), len(rows), len(rows)))
    for sym, label in rows:
        hdr += "    X(%s, %s) \\\n" % (sym, label)
    hdr += "    /* end */\n\n#endif\n"
    changed_beds = write_if_changed(out_beds, hdr)

    if changed_mml or changed_beds:
        print("bedtrim: kept %d of %d beds" % (len(kept), len(songs)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
