#!/bin/sh
#
# Hash the published binaries, write build/CHECKSUMS.txt, and paste a table of
# the result into README.md between its CHECKSUMS markers.
#
# WHY THIS EXISTS.  build/urfinkel.prg and build/urfinkel.d64 are offered as
# downloads, so a visitor needs a way to tell that the file that reached them
# is the file that left here.  Hand-written hashes would be wrong by the second
# commit; hand-written byte counts already were.  This is the one place the
# numbers are produced, and everything that quotes them is filled in from it.
#
# WHAT IT CANNOT DO.  It cannot stamp the README with the SHA of the commit
# that carries it.  That commit's SHA is a hash of its own content, README
# included, so writing the SHA in would change the SHA - a fixed point no hook
# can reach, not a limitation of this script.  What stands in for it:
#
#   * the BUILD DATE, read back out of the .prg where the Makefile stamped it,
#     which is the identity the machine itself draws on the menu;
#   * the GIT BLOB SHA of each binary - git's own content address, computable
#     before any commit exists, and exactly what GitHub stores that file as.
#     Anyone can reproduce it with `git hash-object build/urfinkel.prg`;
#   * a link to that file's commit history, which always resolves to whichever
#     commit last changed it, and so is never stale.
#
# Usage:
#   tools/checksums.sh            regenerate CHECKSUMS.txt and README.md
#   tools/checksums.sh --check    exit 1 if either is out of date, change nothing

set -e

root=$(git rev-parse --show-toplevel)
cd "$root"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

STAMPFILE=build/CHECKSUMS.txt
README=README.md
BEGIN='<!-- CHECKSUMS:START -->'
END='<!-- CHECKSUMS:END -->'
REPO=https://github.com/vonglurt/urfinkel

FILES="build/urfinkel.prg build/urfinkel.d64"

for f in $FILES; do
    if [ ! -f "$f" ]; then
        echo "checksums: $f is missing - run 'make && make disk' first" >&2
        exit 1
    fi
done

# macOS ships `md5` and `shasum`; GNU userlands ship `md5sum` and `sha256sum`.
# Both are emitted in BSD tagged form ("MD5 (path) = hash") so that the two
# algorithms can share one file and each still be checkable with -c.
md5_of() {
    if command -v md5 >/dev/null 2>&1; then md5 -q "$1"
    else md5sum "$1" | cut -d' ' -f1
    fi
}
sha256_of() {
    if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | cut -d' ' -f1
    else sha256sum "$1" | cut -d' ' -f1
    fi
}

size_of() { wc -c < "$1" | tr -d ' '; }

# 56511 -> "56 511", matching how every other byte count in the prose is set.
group() { echo "$1" | sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1 \2/;ta'; }

# The Makefile compiles `date +%Y-%m-%d` into the program and front.c draws it
# on the cabinet, so the binary carries its own build date as plain ASCII.
# Reading it back out is how pre-push identifies a build; the same trick names
# the build here rather than trusting today's clock, which would be a lie for
# any file that was not rebuilt just now.
stamp=$(python3 -c "
import re,sys
d=open('build/urfinkel.prg','rb').read()
m=re.search(rb'20\d\d-\d\d-\d\d',d)
sys.stdout.write(m.group().decode() if m else '')
")
[ -n "$stamp" ] || { echo "checksums: no build stamp in build/urfinkel.prg" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# ---------------------------------------------------------------- the file
{
    echo "UR FINKEL - checksums for the published binaries"
    echo "================================================"
    echo
    echo "Build date $stamp, as stamped into the program and drawn on its menu."
    echo "Generated by tools/checksums.sh; do not edit by hand."
    echo
    echo "These two files are what $REPO"
    echo "offers as downloads. The names below are bare, so save this file into"
    echo "the same folder as the download, then run either of:"
    echo
    echo "    shasum -a 256 -c CHECKSUMS.txt"
    echo "    md5sum -c CHECKSUMS.txt"
    echo
    echo "Each tool warns that the other's lines are improperly formatted and"
    echo "skips them. That is expected - both algorithms share this one file -"
    echo "and the lines it does read are still checked and still reported."
    echo
    for f in $FILES; do
        echo "$(basename "$f")  $(group "$(size_of "$f")") bytes  git blob $(git hash-object "$f")"
    done
    echo
    for f in $FILES; do echo "MD5 ($(basename "$f")) = $(md5_of "$f")"; done
    for f in $FILES; do echo "SHA256 ($(basename "$f")) = $(sha256_of "$f")"; done
} > "$tmp/CHECKSUMS.txt"

# ---------------------------------------------------------------- the table
{
    echo "$BEGIN"
    echo "<!-- Generated by tools/checksums.sh - do not edit between these markers. -->"
    echo
    echo "| File | Bytes | MD5 | SHA-256 |"
    echo "|---|---:|---|---|"
    for f in $FILES; do
        b=$(basename "$f")
        printf '| [%s](%s/raw/main/%s) | %s | `%s` | `%s` |\n' \
            "$b" "$REPO" "$f" "$(group "$(size_of "$f")")" "$(md5_of "$f")" "$(sha256_of "$f")"
    done
    echo
    printf 'Built **%s** — the date the program stamps on its own menu, so a\n' "$stamp"
    echo "download can be identified from the machine without unpacking it."
    echo
    echo "| File | Git blob SHA-1 | Last changed by |"
    echo "|---|---|---|"
    for f in $FILES; do
        b=$(basename "$f")
        printf '| %s | `%s` | [commits touching this file](%s/commits/main/%s) |\n' \
            "$b" "$(git hash-object "$f")" "$REPO" "$f"
    done
    echo
    echo "The blob SHA is git's own address for that content — reproduce it with"
    echo "\`git hash-object build/urfinkel.prg\`, and it is the object GitHub serves"
    echo "the file from. It is used here in place of a commit SHA because a commit"
    echo "cannot state its own: the SHA covers this README, so writing it in would"
    echo "change it. The history link resolves to the right commit instead, and"
    echo "cannot go stale."
    echo
    echo "Machine-readable, and checkable with \`shasum -a 256 -c\` or \`md5sum -c\`:"
    echo "**[build/CHECKSUMS.txt]($REPO/blob/main/$STAMPFILE)**."
    echo
    echo "$END"
} > "$tmp/table.md"

# ------------------------------------------------------------- splice it in
if ! grep -qF "$BEGIN" "$README" || ! grep -qF "$END" "$README"; then
    echo "checksums: $README has no $BEGIN / $END markers" >&2
    exit 1
fi

python3 - "$README" "$tmp/table.md" "$BEGIN" "$END" > "$tmp/README.md" <<'PY'
import sys
readme, table, begin, end = sys.argv[1:5]
text  = open(readme, encoding="utf-8").read()
block = open(table,  encoding="utf-8").read().rstrip("\n")
head, _, rest = text.partition(begin)
_, _, tail    = rest.partition(end)
sys.stdout.write(head + block + tail)
PY

# ------------------------------------------------------------------ deliver
stale=0
cmp -s "$tmp/CHECKSUMS.txt" "$STAMPFILE" || stale=1
cmp -s "$tmp/README.md"     "$README"    || stale=1

if [ "$CHECK" = "1" ]; then
    if [ "$stale" = "1" ]; then
        echo "checksums: $STAMPFILE or $README does not match the binaries." >&2
        echo "           Run 'make checksums' and commit the result." >&2
        exit 1
    fi
    echo "checksums: up to date"
    exit 0
fi

cp "$tmp/CHECKSUMS.txt" "$STAMPFILE"
cp "$tmp/README.md"     "$README"

if [ "$stale" = "1" ]; then
    echo "checksums: $STAMPFILE and $README updated ($stamp)"
else
    echo "checksums: unchanged ($stamp)"
fi

exit 0
