#!/usr/bin/env python3
"""Record the game's big moments as GIFs, and write the page's gallery of them.

    record.py <media.prg> <media.lbl> <out-dir> <page.html> [<README.md>]

WHAT IT DOES.  Boots the labelled media build under xplus4 and lets the URBOT
demo play.  Each moment in EVENTS is a function in the game; a breakpoint on
its entry is how the recorder knows the moment has arrived.  From there it
stops once a frame - on the interrupt's own `inc _music_frames`, which is the
game's idea of a frame - takes a screenshot, and carries on, for as many
frames as the event lasts.  Each run of screenshots becomes one looping GIF.

WHY BREAKPOINTS AND NOT A CLOCK.  The demo is deterministic but the cycle at
which, say, the first capture happens moves every time the code moves.  A
table of cycle counts would be wrong after the next commit; the function
names are not.

THE PAGE.  The gallery in index.html is written between the MEDIA:START and
MEDIA:END markers from the same EVENTS list that made the files, so the page
cannot name a GIF that was not made or caption one with the wrong moment.

It is deterministic enough to re-run, not byte-identical: VICE's warp timing
decides which frame a remote-monitor stop lands on.  So the GIFs are
committed artefacts, regenerated by `make media` when the moments change,
not rebuilt by the hooks on every commit.
"""
import os, re, socket, subprocess, sys, time

from PIL import Image

# name, entry label, frames to record, keep every nth, caption, alt text.
# Ordered as they first happen in a demo; each is recorded on its first hit.
EVENTS = [
    ("curtain",   "_curtain_open", 200, 2, "The cabinet: the curtains open on the menu.",
                  "Theatre curtains drawing back from the UR FINKEL menu"),
    ("throw",     "_throw_lots",    90, 2, "The four lots tumble and land.",
                  "Four tetrahedral lots tumbling across the casting floor"),
    ("move",      "_animate_move",  60, 1, "A piece travels, one character cell at a time.",
                  "A piece gliding along the board"),
    ("capture",   "_burn_apron",    75, 1, "A capture: CAPTURED burns in and goes out.",
                  "CAPTURED in block letters over a bed of flame"),
    ("home",      "_bear_off",     560, 2, "A piece borne off: the laser writes the rule, then the count in block letters, then the race.",
                  "The laser writing bear them off the board to your home, then 1 HOME in block letters, then both sides' pieces home and pips to go"),
    ("victory",   "_victory",      400, 3, "The win: the border flares and the winner's name is cut across the screen.",
                  "The winner's name in block letters, then a gold trophy"),
    ("fireworks", "_fireworks",    300, 2, "Then fireworks, for five minutes, or until a key.",
                  "Fireworks bursting over the trophy, the border flashing"),
]

PORT = 6700 + os.getpid() % 200
FPS = 50


def labels(path):
    out = {}
    for line in open(path):
        p = line.split()
        if len(p) >= 3 and p[2].startswith("."):
            out.setdefault(p[2][1:], int(p[1], 16))
    return out


def frame_tick(prg, music_frames):
    """Address of the handler's `inc _music_frames` - the once-a-frame tick."""
    d = open(prg, "rb").read()
    load = d[0] | d[1] << 8
    pat = bytes([0xEE, music_frames & 0xFF, music_frames >> 8])
    i = d.find(pat, 2)
    if i < 0:
        sys.exit("record: no `inc _music_frames` in the binary")
    return load + i - 2


class Monitor:
    PROMPT = re.compile(rb"\(C:\$[0-9a-f]{4}\) $")

    def __init__(self, port):
        for _ in range(100):
            try:
                self.s = socket.create_connection(("127.0.0.1", port), timeout=2)
                break
            except OSError:
                time.sleep(0.2)
        else:
            sys.exit("record: VICE's monitor never answered")
        self.buf = b""
        # VICE says nothing on connect; the first prompt comes back with the
        # answer to the first command, so ask it something harmless.
        self.cmd("r")

    def read_prompt(self, timeout):
        """Everything up to the next prompt, which is where VICE is waiting."""
        self.s.settimeout(timeout)
        while not self.PROMPT.search(self.buf):
            d = self.s.recv(65536)
            if not d:
                raise EOFError("VICE went away")
            self.buf += d
        out, self.buf = self.buf, b""
        return out.decode(errors="replace")

    def cmd(self, c, timeout=10):
        self.s.sendall((c + "\n").encode())
        return self.read_prompt(timeout)

    def go(self):
        self.s.sendall(b"x\n")


def to_gif(frames, path, every):
    imgs = [Image.open(f).convert("RGB") for f in frames]
    pal = imgs[0].quantize(colors=128)
    q = [im.quantize(palette=pal, dither=Image.Dither.NONE) for im in imgs]
    q[0].save(path, save_all=True, append_images=q[1:], loop=0,
              duration=int(1000 * every / FPS), optimize=True, disposal=1)
    for f in frames:
        os.remove(f)


def page_block(events, media_dir_in_page="media"):
    lines = ["<!-- MEDIA:START -->",
             "<!-- Generated by tools/record.py (make media) - do not edit between these markers. -->",
             '<div class="shots moving">']
    for n, (name, _, _, _, caption, alt) in enumerate(events, 1):
        lines.append('  <figure><img loading="lazy" decoding="async" src="%s/%02d-%s.gif" alt="%s">'
                     % (media_dir_in_page, n, name, alt))
        lines.append("    <figcaption>%s</figcaption></figure>" % caption)
    lines += ["</div>", "<!-- MEDIA:END -->"]
    return "\n".join(lines)


def readme_block(events, outdir):
    """The same gallery for GitHub's front page, as Markdown."""
    lines = ["<!-- MEDIA:START -->",
             "<!-- Generated by tools/record.py (make media) - do not edit between these markers. -->",
             "", "| | |", "|---|---|"]
    cells = ["![%s](%s/%02d-%s.gif)<br>%s" % (alt, outdir, n, name, caption)
             for n, (name, _, _, _, caption, alt) in enumerate(events, 1)]
    for i in range(0, len(cells), 2):
        pair = cells[i:i + 2] + [""] * (2 - len(cells[i:i + 2]))
        lines.append("| %s | %s |" % tuple(pair))
    lines += ["", "<!-- MEDIA:END -->"]
    return "\n".join(lines)


def write_page(page, block):
    s = open(page).read()
    new, n = re.subn(r"<!-- MEDIA:START -->.*?<!-- MEDIA:END -->", lambda _: block, s, flags=re.S)
    if n != 1:
        sys.exit("record: %s has no MEDIA:START/MEDIA:END block" % page)
    if new != s:
        open(page, "w").write(new)


def main():
    prg, lbl, outdir, page = sys.argv[1:5]
    readme = sys.argv[5] if len(sys.argv) > 5 else None
    lab = labels(lbl)
    tick = frame_tick(prg, lab["_music_frames"])
    missing = [e[1] for e in EVENTS if e[1] not in lab]
    if missing:
        sys.exit("record: no label for " + ", ".join(missing))
    os.makedirs(outdir, exist_ok=True)
    tmp = os.path.join(outdir, ".frames")
    os.makedirs(tmp, exist_ok=True)

    vice = subprocess.Popen(
        # -refreshonbreak: VICE under -warp draws only now and then, and a
        # screenshot reads what was last drawn - so without a redraw at each
        # stop a clip is the same frame over and over, or black.
        ["xplus4", "-default", "-warp", "-refreshonbreak", "-sounddev", "dummy", "-jamaction", "5",
         "-remotemonitor", "-remotemonitoraddress", "ip4://127.0.0.1:%d" % PORT,
         "-autostartwithcolon", "-autostart-delay", "4", "-autostart", prg],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        time.sleep(1)
        m = Monitor(PORT)
        # One checkpoint per event, numbered 1..n in EVENTS order, and the
        # frame tick last, disabled until an event arms it.
        for e in EVENTS:
            m.cmd("break %04x" % lab[e[1]])
        tick_no = len(EVENTS) + 1
        m.cmd("break %04x" % tick)
        m.cmd("disable %d" % tick_no)
        todo = set(range(1, len(EVENTS) + 1))
        m.go()

        while todo:
            stop = m.read_prompt(3600)
            hit = re.search(r"#(\d+) \(Stop on", stop)
            if not hit:
                m.go()
                continue
            k = int(hit.group(1))
            if k not in todo:
                m.go()
                continue
            name, _, length, every = EVENTS[k - 1][:4]
            todo.discard(k)
            m.cmd("disable %d" % k)
            m.cmd("enable %d" % tick_no)
            shots = []
            for f in range(length):
                # Another event's breakpoint can stop the machine mid-frame;
                # it is not a frame, so carry on until the tick itself.
                while True:
                    m.go()
                    if "#%d (Stop on" % tick_no in m.read_prompt(600):
                        break
                if f % every == 0:
                    path = os.path.join(tmp, "%s-%04d.png" % (name, f))
                    m.cmd('screenshot "%s" 2' % os.path.abspath(path))
                    shots.append(path)
            m.cmd("disable %d" % tick_no)
            out = os.path.join(outdir, "%02d-%s.gif" % (k, name))
            to_gif(shots, out, every)
            print("record: %-10s %4d frames -> %s (%d KB)"
                  % (name, len(shots), out, os.path.getsize(out) // 1024), flush=True)
            m.go()
    finally:
        vice.kill()
        try:
            os.rmdir(tmp)
        except OSError:
            pass

    write_page(page, page_block(EVENTS))
    print("record: gallery written to", page)
    if readme:
        write_page(readme, readme_block(EVENTS, outdir))
        print("record: gallery written to", readme)


if __name__ == "__main__":
    main()
